version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: UrbanShiftRP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "YOUR_POSTGRES_PASSWORD"
    ports:
      - "5432:5432"
